export const mockMenuData = {
  appetizers: [
    {
      id: "spring-rolls",
      name: "Traditional Spring Rolls",
      description: "Crispy rolls filled with fresh vegetables and aromatic herbs, served with signature dipping sauce",
      longDescription:
        "These spring rolls represent the essence of traditional Vietnamese cooking - simple ingredients transformed through skillful preparation. Our chefs hand-select each vegetable for optimal freshness and crunch, while the delicate rice paper wrapping ensures the perfect texture balance.",
      image: "/6bfcf5f46e7381b53a49902d42c64011.jpg",
      spicy: false,
      popular: true,
      prepTime: "15 min",
      servings: "4 pieces",
      category: "Appetizer",
      origin: "Vietnam",
      ingredients: [
        "Fresh cabbage",
        "Julienned carrots",
        "Bean sprouts",
        "Fresh cilantro",
        "Vietnamese mint",
        "Rice paper wrapping",
        "Premium vegetable oil",
        "Light soy sauce",
        "Sesame oil",
        "Rice vinegar",
      ],
      allergens: ["Soy", "Sesame", "May contain traces of gluten"],
      nutritionalInfo: {
        calories: "180 per serving",
        protein: "4g",
        carbs: "28g",
        fat: "6g",
        fiber: "3g",
      },
      chefNotes:
        "Best enjoyed immediately while the wrapper is still crispy. The contrast between the warm, crispy exterior and cool, fresh interior is what makes this dish special.",
      pairings: ["Jasmine tea", "Light beer", "Vietnamese iced coffee"],
      dietaryTags: ["Vegetarian", "Dairy-free", "Nut-free"],
    },
    {
      id: "dumplings",
      name: "Handmade Pork Dumplings",
      description: "Delicate steamed dumplings with seasoned pork filling and traditional spices",
      longDescription:
        "Our handmade dumplings are crafted using traditional Chinese techniques passed down through generations. Each dumpling is carefully pleated by hand, ensuring the perfect seal and beautiful presentation.",
      image: "/659577601db80b1eaf9dc497f30e02df.jpg",
      spicy: false,
      popular: false,
      prepTime: "12 min",
      servings: "6 pieces",
      category: "Appetizer",
      origin: "China",
      ingredients: [
        "Ground pork",
        "Fresh ginger",
        "Garlic",
        "Scallions",
        "Soy sauce",
        "Sesame oil",
        "Shaoxing wine",
        "White pepper",
        "Dumpling wrappers",
        "Cornstarch",
      ],
      allergens: ["Gluten", "Soy", "Sesame"],
      nutritionalInfo: {
        calories: "220 per serving",
        protein: "12g",
        carbs: "24g",
        fat: "8g",
        fiber: "2g",
      },
      chefNotes:
        "The key to perfect dumplings is the balance of filling to wrapper ratio and proper pleating technique for optimal steaming.",
      pairings: ["Chinese tea", "Rice wine", "Light soy sauce"],
      dietaryTags: ["High protein"],
    },
    {
      id: "satay",
      name: "Grilled Chicken Satay",
      description: "Tender chicken skewers marinated in aromatic spices, served with creamy peanut sauce",
      longDescription:
        "Our chicken satay features tender meat marinated in a complex blend of Thai spices and coconut milk, then grilled over high heat to achieve the perfect char while maintaining juiciness.",
      image: "/0283eb91c9aea880c1c63b2e47d6a13d.jpg",
      spicy: true,
      popular: true,
      prepTime: "18 min",
      servings: "5 skewers",
      category: "Appetizer",
      origin: "Thailand",
      ingredients: [
        "Chicken thigh",
        "Coconut milk",
        "Lemongrass",
        "Galangal",
        "Turmeric",
        "Coriander seeds",
        "Cumin",
        "Peanuts",
        "Palm sugar",
        "Fish sauce",
        "Tamarind paste",
      ],
      allergens: ["Peanuts", "Fish"],
      nutritionalInfo: {
        calories: "280 per serving",
        protein: "24g",
        carbs: "8g",
        fat: "16g",
        fiber: "2g",
      },
      chefNotes:
        "Marinate for at least 4 hours for maximum flavor penetration. The peanut sauce should balance sweet, salty, and spicy elements.",
      pairings: ["Thai beer", "Coconut water", "Thai iced tea"],
      dietaryTags: ["High protein", "Gluten-free"],
    },
    {
      id: "gyoza",
      name: "Pan-Fried Gyoza",
      description: "Crispy bottom dumplings filled with pork and vegetables, served with soy-vinegar dipping sauce",
      longDescription:
        "These Japanese pan-fried dumplings achieve the perfect texture with a crispy bottom and tender steamed top, filled with a savory mixture of pork and vegetables.",
      image: "/a8b16985826449598c595e1d0b1caf8b.jpg",
      spicy: false,
      popular: true,
      prepTime: "14 min",
      servings: "6 pieces",
      category: "Appetizer",
      origin: "Japan",
      ingredients: [
        "Ground pork",
        "Napa cabbage",
        "Garlic chives",
        "Ginger",
        "Garlic",
        "Soy sauce",
        "Sesame oil",
        "Mirin",
        "Gyoza wrappers",
        "Vegetable oil",
      ],
      allergens: ["Gluten", "Soy", "Sesame"],
      nutritionalInfo: {
        calories: "240 per serving",
        protein: "14g",
        carbs: "22g",
        fat: "10g",
        fiber: "3g",
      },
      chefNotes:
        "The key is achieving the perfect golden-brown bottom while steaming the top portion. Use just enough water for proper steaming.",
      pairings: ["Japanese beer", "Sake", "Green tea"],
      dietaryTags: ["High protein"],
    },
    {
      id: "bao-buns",
      name: "Steamed Bao Buns",
      description: "Fluffy steamed buns filled with braised pork belly and pickled vegetables",
      longDescription:
        "Our steamed bao buns are made with a special dough that creates the signature fluffy, cloud-like texture. The pork belly is braised for hours until tender and flavorful.",
      image: "/2afae01516e7aade2d378759ded385d6.jpg",
      spicy: false,
      popular: true,
      prepTime: "16 min",
      servings: "3 buns",
      category: "Appetizer",
      origin: "China",
      ingredients: [
        "Pork belly",
        "Flour",
        "Yeast",
        "Sugar",
        "Baking powder",
        "Soy sauce",
        "Shaoxing wine",
        "Star anise",
        "Pickled vegetables",
        "Hoisin sauce",
      ],
      allergens: ["Gluten", "Soy"],
      nutritionalInfo: {
        calories: "320 per serving",
        protein: "18g",
        carbs: "28g",
        fat: "16g",
        fiber: "2g",
      },
      chefNotes:
        "The bun dough requires proper proofing for the characteristic fluffy texture. The pork should be fork-tender after braising.",
      pairings: ["Chinese tea", "Light beer", "Rice wine"],
      dietaryTags: ["High protein"],
    },
    {
      id: "tempura",
      name: "Mixed Tempura",
      description: "Light and crispy tempura vegetables and prawns with tentsuyu dipping sauce",
      longDescription:
        "Our tempura batter is made fresh and kept ice-cold for the lightest, crispiest coating. The vegetables and prawns are carefully selected for optimal texture and flavor.",
      image: "/1e654cc7ab33e3cb80031552e4c6e81f.jpg",
      spicy: false,
      popular: false,
      prepTime: "20 min",
      servings: "8 pieces",
      category: "Appetizer",
      origin: "Japan",
      ingredients: [
        "Tiger prawns",
        "Sweet potato",
        "Eggplant",
        "Green beans",
        "Shishito peppers",
        "Tempura flour",
        "Ice water",
        "Dashi",
        "Mirin",
        "Soy sauce",
      ],
      allergens: ["Shellfish", "Gluten"],
      nutritionalInfo: {
        calories: "290 per serving",
        protein: "16g",
        carbs: "32g",
        fat: "12g",
        fiber: "4g",
      },
      chefNotes:
        "Keep the batter cold and don't overmix. The oil temperature is crucial - too hot and the outside burns before the inside cooks.",
      pairings: ["Japanese beer", "Sake", "Green tea"],
      dietaryTags: ["High protein"],
    },
  ],
  mains: [
    {
      id: "pad-thai",
      name: "Authentic Pad Thai",
      description:
        "Stir-fried rice noodles with fresh shrimp, crispy tofu, bean sprouts, and house-made tamarind sauce",
      longDescription:
        "This iconic Thai dish requires precise timing and technique. Our chefs use traditional flat rice noodles, soaked to the perfect texture, then stir-fried over high heat with our signature tamarind-based sauce.",
      image: "/3d2887ae70ea5ee838a659e552bada92.jpg",
      spicy: true,
      popular: true,
      prepTime: "20 min",
      servings: "1 portion",
      category: "Main Course",
      origin: "Thailand",
      ingredients: [
        "Fresh rice noodles",
        "Tiger prawns",
        "Firm tofu",
        "Free-range eggs",
        "Bean sprouts",
        "Tamarind paste",
        "Fish sauce",
        "Palm sugar",
        "Crushed peanuts",
        "Fresh lime",
        "Chili flakes",
      ],
      allergens: ["Shellfish", "Eggs", "Fish", "Peanuts", "Soy"],
      nutritionalInfo: {
        calories: "520 per serving",
        protein: "28g",
        carbs: "65g",
        fat: "18g",
        fiber: "4g",
      },
      chefNotes:
        "The secret is in the wok hei - the breath of the wok. High heat and quick cooking preserve the texture of the noodles while developing complex flavors.",
      pairings: ["Thai iced tea", "Singha beer", "Coconut water"],
      dietaryTags: ["Gluten-free option available", "High protein"],
    },
    {
      id: "beef-curry",
      name: "Red Beef Curry",
      description: "Tender beef slow-cooked in aromatic red curry with coconut milk, served with jasmine rice",
      longDescription:
        "Our red curry is made from scratch using traditional Thai curry paste, combining dried chilies, lemongrass, galangal, and aromatic spices. The beef is slow-cooked until fork-tender.",
      image: "/11a6cfec7cd161c41239bf3a02346da5.jpg",
      spicy: true,
      popular: false,
      prepTime: "25 min",
      servings: "1 portion",
      category: "Main Course",
      origin: "Thailand",
      ingredients: [
        "Beef chuck",
        "Red curry paste",
        "Coconut milk",
        "Thai basil",
        "Bamboo shoots",
        "Thai eggplant",
        "Fish sauce",
        "Palm sugar",
        "Kaffir lime leaves",
        "Jasmine rice",
      ],
      allergens: ["Fish"],
      nutritionalInfo: {
        calories: "580 per serving",
        protein: "32g",
        carbs: "45g",
        fat: "28g",
        fiber: "3g",
      },
      chefNotes:
        "The curry paste should be fried until fragrant before adding coconut milk. This releases the essential oils and creates depth of flavor.",
      pairings: ["Thai beer", "Coconut water", "Jasmine tea"],
      dietaryTags: ["Gluten-free", "High protein"],
    },
    {
      id: "teriyaki-salmon",
      name: "Glazed Teriyaki Salmon",
      description: "Fresh Atlantic salmon glazed with signature teriyaki sauce, served with steamed vegetables",
      longDescription:
        "Our teriyaki salmon features premium Atlantic salmon, glazed with our house-made teriyaki sauce that balances sweet mirin, savory soy sauce, and aromatic sake.",
      image: "/bd9e2f4f9f42c513ea37c2e9dc56250f.jpg",
      spicy: false,
      popular: true,
      prepTime: "22 min",
      servings: "1 portion",
      category: "Main Course",
      origin: "Japan",
      ingredients: [
        "Atlantic salmon fillet",
        "Soy sauce",
        "Mirin",
        "Sake",
        "Sugar",
        "Ginger",
        "Garlic",
        "Sesame seeds",
        "Steamed broccoli",
        "Jasmine rice",
      ],
      allergens: ["Fish", "Soy", "Sesame"],
      nutritionalInfo: {
        calories: "450 per serving",
        protein: "35g",
        carbs: "32g",
        fat: "20g",
        fiber: "4g",
      },
      chefNotes:
        "The salmon should be cooked to medium for optimal texture. The teriyaki glaze should be reduced until it coats the back of a spoon.",
      pairings: ["Sake", "Japanese beer", "Green tea"],
      dietaryTags: ["High protein", "Omega-3 rich"],
    },
    {
      id: "ramen",
      name: "Traditional Ramen Bowl",
      description: "Rich tonkotsu broth with handmade noodles, tender pork belly, soft-boiled egg, and fresh scallions",
      longDescription:
        "Our ramen features a rich tonkotsu broth that's simmered for 18 hours to achieve the perfect creamy consistency. The noodles are made fresh daily and the pork belly is braised until melt-in-your-mouth tender.",
      image: "/691f332883b246057aa03d5ae7ebd34d.jpg",
      spicy: false,
      popular: true,
      prepTime: "18 min",
      servings: "1 bowl",
      category: "Main Course",
      origin: "Japan",
      ingredients: [
        "Fresh ramen noodles",
        "Pork bones",
        "Pork belly",
        "Soft-boiled egg",
        "Scallions",
        "Nori seaweed",
        "Bamboo shoots",
        "Garlic",
        "Ginger",
        "Miso paste",
      ],
      allergens: ["Gluten", "Eggs", "Soy"],
      nutritionalInfo: {
        calories: "620 per serving",
        protein: "28g",
        carbs: "55g",
        fat: "32g",
        fiber: "3g",
      },
      chefNotes:
        "The broth is the soul of ramen. It takes 18 hours of slow simmering to achieve the perfect milky white tonkotsu broth.",
      pairings: ["Japanese beer", "Sake", "Green tea"],
      dietaryTags: ["High protein"],
    },
    {
      id: "duck-pancakes",
      name: "Peking Duck Pancakes",
      description: "Crispy duck served with thin pancakes, cucumber, scallions, and hoisin sauce",
      longDescription:
        "Our Peking duck is prepared using traditional methods - the duck is air-dried and roasted in a special oven to achieve the signature crispy skin and tender meat.",
      image: "/47f70bcc3d916ebb436e56d44c00043f.jpg",
      spicy: false,
      popular: true,
      prepTime: "30 min",
      servings: "8 pancakes",
      category: "Main Course",
      origin: "China",
      ingredients: [
        "Whole duck",
        "Thin pancakes",
        "Cucumber",
        "Scallions",
        "Hoisin sauce",
        "Five-spice powder",
        "Maltose",
        "Soy sauce",
        "Shaoxing wine",
        "Ginger",
      ],
      allergens: ["Gluten", "Soy"],
      nutritionalInfo: {
        calories: "680 per serving",
        protein: "42g",
        carbs: "35g",
        fat: "38g",
        fiber: "2g",
      },
      chefNotes:
        "The duck skin should be lacquered and crispy, while the meat remains succulent. The pancakes should be warm and pliable.",
      pairings: ["Chinese tea", "Plum wine", "Light beer"],
      dietaryTags: ["High protein"],
    },
    {
      id: "korean-bbq",
      name: "Korean BBQ Bulgogi",
      description: "Marinated beef grilled to perfection, served with kimchi, rice, and traditional banchan",
      longDescription:
        "Our bulgogi features thinly sliced beef marinated in a sweet and savory sauce with Asian pear, soy sauce, and sesame oil. Grilled over high heat for the perfect caramelization.",
      image: "/a58d9a0659f6a231ee2932b3b97b00e9.jpg",
      spicy: true,
      popular: false,
      prepTime: "24 min",
      servings: "1 portion",
      category: "Main Course",
      origin: "Korea",
      ingredients: [
        "Thinly sliced beef",
        "Asian pear",
        "Soy sauce",
        "Sesame oil",
        "Garlic",
        "Ginger",
        "Brown sugar",
        "Kimchi",
        "Steamed rice",
        "Mixed banchan",
      ],
      allergens: ["Soy", "Sesame"],
      nutritionalInfo: {
        calories: "550 per serving",
        protein: "38g",
        carbs: "42g",
        fat: "24g",
        fiber: "3g",
      },
      chefNotes:
        "The beef should be sliced paper-thin against the grain. The marinade needs at least 2 hours to penetrate the meat properly.",
      pairings: ["Korean beer", "Soju", "Barley tea"],
      dietaryTags: ["High protein", "Fermented foods"],
    },
    {
      id: "sushi-platter",
      name: "Chef's Sushi Selection",
      description: "Assorted fresh sushi and sashimi prepared by our master sushi chef",
      longDescription:
        "Our sushi selection features the freshest fish, sourced daily and prepared by our master sushi chef. Each piece is crafted with precision and attention to traditional techniques.",
      image: "/3e8ea93eba05217c9f0662f37bac3696.jpg",
      spicy: false,
      popular: true,
      prepTime: "25 min",
      servings: "12 pieces",
      category: "Main Course",
      origin: "Japan",
      ingredients: [
        "Fresh tuna",
        "Fresh salmon",
        "Yellowtail",
        "Sea bream",
        "Sushi rice",
        "Nori seaweed",
        "Wasabi",
        "Pickled ginger",
        "Soy sauce",
        "Rice vinegar",
      ],
      allergens: ["Fish", "Soy"],
      nutritionalInfo: {
        calories: "480 per serving",
        protein: "32g",
        carbs: "58g",
        fat: "8g",
        fiber: "1g",
      },
      chefNotes:
        "The rice temperature should match body temperature when serving. Each piece should be consumed immediately for optimal texture.",
      pairings: ["Sake", "Japanese beer", "Green tea"],
      dietaryTags: ["High protein", "Low fat"],
    },
    {
      id: "mapo-tofu",
      name: "Mapo Tofu",
      description: "Silky tofu in spicy Sichuan sauce with ground pork and fermented black beans",
      longDescription:
        "This classic Sichuan dish features silky tofu in a fiery sauce made with doubanjiang (fermented bean paste), Sichuan peppercorns, and ground pork for authentic numbing heat.",
      image: "/48bb7acc4f7fd30a293db818035652d1.jpg",
      spicy: true,
      popular: false,
      prepTime: "16 min",
      servings: "1 portion",
      category: "Main Course",
      origin: "China",
      ingredients: [
        "Silky tofu",
        "Ground pork",
        "Doubanjiang",
        "Sichuan peppercorns",
        "Garlic",
        "Ginger",
        "Scallions",
        "Soy sauce",
        "Chicken stock",
        "Cornstarch",
      ],
      allergens: ["Soy"],
      nutritionalInfo: {
        calories: "380 per serving",
        protein: "22g",
        carbs: "12g",
        fat: "28g",
        fiber: "2g",
      },
      chefNotes:
        "The tofu should be silky and the sauce should have the characteristic numbing sensation from Sichuan peppercorns.",
      pairings: ["Chinese tea", "Rice wine", "Light beer"],
      dietaryTags: ["High protein", "Spicy"],
    },
  ],
  desserts: [
    {
      id: "mochi",
      name: "Artisan Mochi Ice Cream",
      description:
        "Handcrafted Japanese rice cake filled with premium ice cream in vanilla, strawberry, and green tea flavors",
      longDescription:
        "Our mochi is made fresh daily using traditional Japanese techniques. The glutinous rice is steamed and pounded to achieve the perfect chewy texture, then carefully wrapped around premium ice cream.",
      image: "/9f5c48bd9fa37758289e8847f9c4cf07.jpg",
      spicy: false,
      popular: true,
      prepTime: "5 min",
      servings: "3 pieces",
      category: "Dessert",
      origin: "Japan",
      ingredients: [
        "Premium glutinous rice flour",
        "Cane sugar",
        "Filtered water",
        "Potato starch",
        "Premium vanilla ice cream",
        "Fresh strawberry ice cream",
        "Ceremonial grade matcha ice cream",
      ],
      allergens: ["Dairy", "May contain traces of nuts"],
      nutritionalInfo: {
        calories: "95 per piece",
        protein: "2g",
        carbs: "18g",
        fat: "2g",
        fiber: "0g",
      },
      chefNotes:
        "Serve immediately for the best contrast between the soft mochi exterior and frozen ice cream center. The temperature difference is essential to the experience.",
      pairings: ["Green tea", "Sake", "Japanese whisky"],
      dietaryTags: ["Vegetarian", "Gluten-free"],
    },
    {
      id: "mango-sticky-rice",
      name: "Mango Sticky Rice",
      description: "Sweet coconut sticky rice topped with fresh mango slices and toasted coconut flakes",
      longDescription:
        "This beloved Thai dessert features glutinous rice cooked in rich coconut milk and sugar, served with perfectly ripe mango slices and a drizzle of coconut cream.",
      image: "/d1ad6734024c118bd3af9ca71a4ec5d3.jpg",
      spicy: false,
      popular: false,
      prepTime: "8 min",
      servings: "1 portion",
      category: "Dessert",
      origin: "Thailand",
      ingredients: [
        "Glutinous rice",
        "Coconut milk",
        "Palm sugar",
        "Salt",
        "Fresh mango",
        "Toasted coconut flakes",
        "Pandan leaves",
      ],
      allergens: ["May contain traces of nuts"],
      nutritionalInfo: {
        calories: "320 per serving",
        protein: "4g",
        carbs: "68g",
        fat: "8g",
        fiber: "2g",
      },
      chefNotes:
        "The rice should be tender but still have a slight bite. The mango must be perfectly ripe for the best flavor balance.",
      pairings: ["Thai tea", "Coconut water", "Light dessert wine"],
      dietaryTags: ["Vegan", "Gluten-free"],
    },
    {
      id: "matcha-cheesecake",
      name: "Matcha Cheesecake",
      description: "Creamy Japanese cheesecake infused with premium matcha, served with red bean ice cream",
      longDescription:
        "Our Japanese-style cheesecake is lighter and fluffier than traditional versions, infused with ceremonial grade matcha for an authentic bitter-sweet flavor profile.",
      image: "/09228ac564e50702c3893445f27ff830.jpg",
      spicy: false,
      popular: true,
      prepTime: "6 min",
      servings: "1 slice",
      category: "Dessert",
      origin: "Japan",
      ingredients: [
        "Cream cheese",
        "Ceremonial grade matcha",
        "Eggs",
        "Sugar",
        "Heavy cream",
        "Butter",
        "Graham crackers",
        "Red bean ice cream",
      ],
      allergens: ["Dairy", "Eggs", "Gluten"],
      nutritionalInfo: {
        calories: "380 per serving",
        protein: "8g",
        carbs: "32g",
        fat: "24g",
        fiber: "1g",
      },
      chefNotes:
        "The matcha should be sifted to avoid lumps. The cheesecake should be light and airy, not dense like American-style cheesecake.",
      pairings: ["Green tea", "Sake", "Coffee"],
      dietaryTags: ["Vegetarian"],
    },
    {
      id: "dorayaki",
      name: "Traditional Dorayaki",
      description: "Fluffy pancake sandwich filled with sweet red bean paste and fresh whipped cream",
      longDescription:
        "These Japanese pancake sandwiches feature fluffy, honey-sweetened pancakes filled with traditional sweet red bean paste and a touch of fresh whipped cream.",
      image: "/cbd1095d4f97fb36edb9771809b7b8ef.jpg",
      spicy: false,
      popular: false,
      prepTime: "7 min",
      servings: "2 pieces",
      category: "Dessert",
      origin: "Japan",
      ingredients: [
        "Flour",
        "Eggs",
        "Sugar",
        "Honey",
        "Baking soda",
        "Sweet red bean paste",
        "Fresh whipped cream",
        "Vanilla extract",
      ],
      allergens: ["Gluten", "Eggs", "Dairy"],
      nutritionalInfo: {
        calories: "280 per serving",
        protein: "6g",
        carbs: "52g",
        fat: "6g",
        fiber: "3g",
      },
      chefNotes:
        "The pancakes should be golden brown and fluffy. Don't overfill with red bean paste or it will squeeze out when eating.",
      pairings: ["Green tea", "Milk", "Coffee"],
      dietaryTags: ["Vegetarian"],
    },
    {
      id: "sesame-balls",
      name: "Golden Sesame Balls",
      description: "Deep-fried glutinous rice balls filled with sweet red bean paste and coated with sesame seeds",
      longDescription:
        "These crispy Chinese desserts feature a chewy glutinous rice exterior coated in sesame seeds, with a sweet red bean paste center that becomes molten when fried.",
      image: "/52a7dea9a8f0e1b16a0b504182419160.jpg",
      spicy: false,
      popular: true,
      prepTime: "12 min",
      servings: "4 balls",
      category: "Dessert",
      origin: "China",
      ingredients: [
        "Glutinous rice flour",
        "Water",
        "Sugar",
        "Sweet red bean paste",
        "White sesame seeds",
        "Vegetable oil for frying",
      ],
      allergens: ["Sesame"],
      nutritionalInfo: {
        calories: "240 per serving",
        protein: "4g",
        carbs: "42g",
        fat: "8g",
        fiber: "2g",
      },
      chefNotes:
        "The oil temperature is crucial - too hot and the outside burns before the inside cooks. The balls should be golden and crispy outside, chewy inside.",
      pairings: ["Chinese tea", "Jasmine tea", "Light dessert wine"],
      dietaryTags: ["Vegan", "Gluten-free"],
    },
    {
      id: "taiyaki",
      name: "Fish-Shaped Taiyaki",
      description: "Warm fish-shaped pastry filled with sweet custard or red bean paste",
      longDescription:
        "These iconic Japanese fish-shaped pastries are made fresh to order in special molds, creating a crispy exterior and warm, sweet filling inside.",
      image: "/4f2b6652beaaa46278446d149f4ba704.jpg",
      spicy: false,
      popular: false,
      prepTime: "10 min",
      servings: "2 pieces",
      category: "Dessert",
      origin: "Japan",
      ingredients: [
        "Flour",
        "Eggs",
        "Sugar",
        "Milk",
        "Baking powder",
        "Sweet custard filling",
        "Red bean paste",
        "Vanilla extract",
      ],
      allergens: ["Gluten", "Eggs", "Dairy"],
      nutritionalInfo: {
        calories: "220 per serving",
        protein: "5g",
        carbs: "38g",
        fat: "6g",
        fiber: "2g",
      },
      chefNotes:
        "The batter should be smooth and the molds properly heated. Serve warm for the best experience - the filling should be hot and creamy.",
      pairings: ["Green tea", "Milk", "Hot chocolate"],
      dietaryTags: ["Vegetarian"],
    },
  ],
}

// Helper function to get all dishes
export const getAllDishes = () => {
  return [...mockMenuData.appetizers, ...mockMenuData.mains, ...mockMenuData.desserts]
}

// Helper function to get dish by ID
export const getDishById = (id: string) => {
  return getAllDishes().find((dish) => dish.id === id)
}
